name: Build and Deploy

on:
  push:
    branches:
      - main  # Change selon ta branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construire le JAR
        run: mvn clean package

      - name: Construire l’image Docker
        run: |
          docker build -t image-hrapi:latest .
          docker tag image-hrapi:latest fplaisantntico/image-hrapi:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push fplaisantntico/image-hrapi:latest

      - name: Déployer avec Docker Compose
        run: docker-compose up -d